### ISSUE TITLE
Node.js 16 actions are deprecated

### ISSUE THREAD

**Issue by elmoritz** [wechuli/pull-request-updater#7]
Thank you for your work on this nice action.

We noticed that this warning pops up when we use it.
Any chance you could do an update?

Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: wechuli/pull-request-updater@v2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by wechuli** [comment]
Oh, I thought I had done this, looks like my tests were using `main`. Created a new release at `v2.1.0`tag  and moved `v2` to it. Thanks for catching that.

**Comment by wechuli** [comment]
Closing as resolved

**Comment by elmoritz** [comment]
Thank you very much and especially because the response was so fast I almost missed it.
